name: flutter_recorder
description: >-
  A low-level audio recorder plugin which uses miniaudio as
  backend. Detect silence and save to WAV audio file. Audio
  wave, FFT and volume level can be get in real-time.
version: 2.0.1
issue_tracker: https://github.com/alnitak/flutter_recorder/issues
homepage: https://github.com/alnitak/flutter_recorder
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
topics:
  - audio
  - recorder
  - visualizer

screenshots:
  - description: "flutter_recording logo"
    path: images/recorder.png

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  code_assets: ^2.0.0
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  hooks: ^2.2.0
  logging: ^1.3.0
  meta: ^1.15.0
  native_toolchain_c: ^0.19.4
  plugin_platform_interface: ^2.1.8
  web: ^1.1.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: flutter.recorder.flutter_recorder
        pluginClass: FlutterRecorderPlugin
        ffiPlugin: true
      ios:
        pluginClass: FlutterRecorderPlugin
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        pluginClass: FlutterRecorderPlugin
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
        default_package: true

  assets:
    # These assets are only needed for the web platform.
    # https://github.com/flutter/flutter/pull/176393
    - path: web/worker.dart.js
      platforms: [web]
    - path: web/init_recorder_module.dart.js
      platforms: [web]
    - path: web/libflutter_recorder_plugin.js
      platforms: [web]
    - path: web/libflutter_recorder_plugin.wasm
      platforms: [web]
    - path: web/libflutter_recorder_plugin_mt.js
      platforms: [web]
    - path: web/libflutter_recorder_plugin_mt.wasm
      platforms: [web]

funding:
  - https://github.com/sponsors/alnitak
